// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"hooks/ent/schema"
	"hooks/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userHooks := schema.User{}.Hooks()
	user.Hooks[0] = userHooks[0]
}

const (
	Version = "v0.12.5"                                         // Version of ent codegen.
	Sum     = "h1:KREM5E4CSoej4zeGa88Ou/gfturAnpUv0mzAjch1sj4=" // Sum of ent codegen.
)
