// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Queue is the predicate function for queue builders.
type Queue func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
